# Generated by Django 4.1.3 on 2022-11-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netboxattachment',
            options={'ordering': ('name', 'pk'), 'verbose_name': 'NetBox Attachment',
                     'verbose_name_plural': 'NetBox Attachments'},
        ),
        migrations.AddField(
            model_name='netboxattachment',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
