# Generated by Django 4.1.3 on 2022-11-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_attachments', '0002_alter_netboxattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netboxattachment',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
