# Generated by Django 5.0.6 on 2024-07-16 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_attachments", "0005_netboxattachment_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="netboxattachment",
            old_name="content_type",
            new_name="object_type",
        ),
    ]
